In [11]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import cross_validation,preprocessing
from sklearn.linear_model import LinearRegression



/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [141]:
df = pd.read_csv("/home/shivam/BE Project/Crime committed against Women/CAW.csv")
df

Year   Rape  Kidnapping and Abduction of Women & Girls  Dowry Deaths  \
0   2001  16075                                      14645          6851   
1   2002  16373                                      14506          6822   
2   2003  15847                                      13296          6208   
3   2004  18233                                      15578          7026   
4   2005  18359                                      15750          6787   
5   2006  19348                                      17414          7618   
6   2007  20737                                      20416          8093   
7   2008  21467                                      22939          8172   
8   2009  21397                                      25741          8383   
9   2010  22172                                      29795          8391   
10  2011  24206                                      35565          8618   
11  2012  24923                                      38262          8233   
12  2013  33707                                      51881          8083   
13  2014  36735                                      57311          8455   

    Assault on women with intent to outrage her modesty  \
0                                               34124     
1                                               33943     
2                                               32939     
3                                               34567     
4                                               34175     
5                                               36617     
6                                               38734     
7                                               40413     
8                                               38711     
9                                               40613     
10                                              42968     
11                                              45351     
12                                              70739     
13                                              82235     

    Insult to the modesty of Women  Cruelty by Husband or his relatives  \
0                             9746                                49170   
1                            10155                                49237   
2                            12325                                50703   
3                            10001                                58121   
4                             9984                                58319   
5                             9966                                63128   
6                            10950                                75930   
7                            12214                                81344   
8                            11009                                89546   
9                             9961                                94041   
10                            8570                                99135   
11                            9173                               106527   
12                           12589                               118866   
13                            9735                               122877   

    Importation of Girls from Foreign Country  Immoral Traffic (P) Act  \
0                                         114                     8796   
1                                          76                     6598   
2                                          46                     5510   
3                                          89                     5748   
4                                         149                     5908   
5                                          67                     4541   
6                                          61                     3568   
7                                          67                     2660   
8                                          48                     2474   
9                                          36                     2499   
10                                   

In [258]:
X = df.iloc[:,:-1].values
y = df.iloc[:,12].values
X_train,X_test,y_train,y_test = cross_validation.train_test_split(X,y,test_size=0.2)

regressor = LinearRegression()
regressor.fit(X_train,y_train)

print "Your Test Set is:- \n",X_test
#X_tst = np.array([2015, 0, 0,  0, 0, 0, 0, 0, 0, 0,  0, 0])
accuracy = regressor.score(X_test,y_test)
print "\nYour Prediction has the accuracy of-",accuracy*100,"%"

y_prediction = regressor.predict(X_test)
print "\nPredicted Total Crime for above given years is:-\n",y_prediction

Your Test Set is:- 
[[ 2009 21397 25741  8383 38711 11009 89546    48  2474  5650   845     0]
 [ 2005 18359 15750  6787 34175  9984 58319   149  5908  3204  2917     1]
 [ 2010 22172 29795  8391 40613  9961 94041    36  2499  5182   895     0]]

Your Prediction has the accuracy of- 99.999999987 %

Predicted Total Crime for above given years is:-
[ 203804.06126778  155553.3971474   213584.69932794]


In [259]:
rapeX = df.iloc[:,0].values
rapeY = df.iloc[:,1].values

#rapeX_train,rapeX_test,rapeY_train,rapeY_test = cross_validation.train_test_split(rapeX,rapeY,test_size=0.1)
rapeX_test = np.array([2015,2016,2017,2018,2019,2020])

print "Your Test Set is:- \n",rapeX_test

clf=LinearRegression()    #clf is the regression classifier
clf.fit(rapeX.reshape(-1, 1),rapeY)   #reshape to convert it from 1 dimentional array to 2D array.
#accuracy = clf.score(rapeX_test.reshape(-1, 1),rapeY_test)
#print accuracy
rapePredict = clf.predict(rapeX_test.reshape(-1,1))
print "\nPredicted Total Crime for above given years is:-\n",rapePredict

Your Test Set is:- 
[2015 2016 2017 2018 2019 2020]

Predicted Total Crime for above given years is:-
[ 32146.15384615  33483.93626374  34821.71868132  36159.5010989
  37497.28351648  38835.06593407]


In [239]:
'''plt.scatter(rapeX,rapeY,color = 'red')
plt.plot(rapeX, clf.predict(rapeX.reshape(1,-1)), color = 'blue')
plt.title("Rape Crime against Women")
plt.xlabel("Year")
plt.ylabel("Rape Cases Reported")
plt.show()

'''

'plt.scatter(rapeX,rapeY,color = \'red\')\nplt.plot(rapeX, clf.predict(rapeX.reshape(1,-1)), color = \'blue\')\nplt.title("Rape Crime against Women")\nplt.xlabel("Year")\nplt.ylabel("Rape Cases Reported")\nplt.show()\n\n'